### ISSUE TITLE
Inconsistency, accuracy, Des Clustering

### ISSUE THREAD

**Issue by lachhebo** [scikit-learn-contrib/DESlib#158]
I have spotted a really stange behaviour of the Des Clustering model. 

When i am using this model with 5 differents estimators and a very unbalanced datasets, i get a precision and a recall equal to 0, actually, the majority class is predicted almost every time for a new observation.

I think it is caused by the fact that estimators are selectionned based on their accuracy on each cluster which leads to the prediction of the majority class for every new observation. 

A solution would be to be able to use others metrics instead of accuracy (like F-score), do you think it is possible ?

**Comment by Menelau** [comment]
@lachhebo You are right, the fact the estimators are selected according to accuracy leads to a bias towards the majority class. 

It is possible to change this behavior. In fact, I believe the fix would be very simple, only requiring changing inside the method `_preprocess_clusters` to consider a metric suitable for imbalanced learning in order to rank the N best base classifiers. Maybe we could add an input parameter to the DES Clustering technique where the user can specify the metric used to rank the best models for each cluster.

**Comment by Menelau** [comment]
Fixed in #161
