### ISSUE TITLE
ValueError: could not broadcast input array from shape ... into shape ...

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#181]
I got this error. I could feel it comes from Stack classifier.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-63c45eba5c76> in <module>
     12                                                       landscape_vertical_session1_training_label,
     13                                                       landscape_vertical_session1_validation_label,
---> 14                                                       landscape_vertical_session1_test_label)
     15 
     16 average_result_landscape_vertical_session1 = np.mean(result_landscape_vertical_session1,axis=1)

<ipython-input-9-3ef7ee825dad> in train_test_model(training_set, validation_set, test_set, training_label, validation_label, test_label)
     84         single_best = SingleBest(pool_classifiers)
     85 
---> 86         model_stacked = stacked.fit(X_dsel, y_dsel)
     87         model_static_selection = static_selection.fit(X_dsel, y_dsel)
     88         model_single_best = single_best.fit(X_dsel, y_dsel)

~\Anaconda3\lib\site-packages\deslib\static\stacked.py in fit(self, X, y)
     63         super(StackedClassifier, self).fit(X, y)
     64 
---> 65         base_preds = self._predict_proba_base(X)
     66 
     67         # Prepare the meta-classifier

~\Anaconda3\lib\site-packages\deslib\static\stacked.py in _predict_proba_base(self, X)
    147 
    148         for index, clf in enumerate(self.pool_classifiers_):
--> 149             probabilities[:, index] = clf.predict_proba(X)
    150         return probabilities.reshape(X.shape[0],
    151                                      self.n_classifiers_ * self.n_classes_)

ValueError: could not broadcast input array from shape (154,2) into shape (154,1)
```
Below is the file that I'm using, you can simply load the data:
https://www.dropbox.com/sh/3q2dm1tdde0etl5/AAB2RJbyyrOf2t9dmwoDNjzoa?dl=0

**Comment by Menelau** [comment]
@jayahm Hello,

Thanks for providing an example, as I suspected before, the problem occurs because of the number of classes passed down for training. The problem occurs when dealing with user==5. In this case, the y_train contain classes [0, 6], while y_dsel contain only class [0]. So the base classifiers were fitted for a two-class classification problem and hence produces an array of [n_samples, 2] when the `predict_proba ` method is called. However, the meta-classifier (in the stacking method) is receiving just one class for training. In this case, both the base models and the meta-models should be trained with the same number of classes. That is the reason the array's shape becomes incompatible. 

So you will need to change the input data in a way that all of them contain at least the same classes. One alternative is to use oversampling methods to generate synthetic examples for the minority classes using the imbalanced learning library: https://imbalanced-learn.readthedocs.io/en/stable/api.html#module-imblearn.over_sampling

**Comment by jayahm** [comment]
Oh, I see. Thanks! Now, I understand what happened.
