### ISSUE TITLE
predict_proba from different methods are the same

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#184]
Hi.

For each DCS method in the package, I used .predict_proba to produce the probability scores.

For example,
```
ola.predict_proba(x_test)
lca.predict_proba(x_test)
```

and so on.

I wonder why the scores produced are the same for all methods?

each of them suppose to chose the score produced by the selected classifier, right?

Note: Accuracy are not same.

**Comment by Menelau** [comment]
Hello @jayahm 

DCS methods do use the probability estimates of the selected base classifier when calling the predict_proba. And I can guarantee you that the predict_proba of different DCS models gives different results (as they may differ in the selected classifier for each example). 

I created one example that shows the predict_proba of different DCS methods gives different outputs. You can check the example in the following gist: https://gist.github.com/Menelau/6a5b1fb82cb3ef5618c358a8a2fbde99

In your case, it could be a scenario where all DCS methods agree that the same classifier is the competent one. So that the probabilities estimates are the same.

**Comment by jayahm** [comment]
Maybe I misunderstood something. Thank you for the clarification.
