### ISSUE TITLE
Why RRC requires the number of neighbours?

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#210]
Hi,

I realize RRC and other methods where the region of competence is based on potential function requires the number of k.

What I 8understood is that, they use the whole DSEL.

Why the class of these methods, we still need to set k?

**Comment by Menelau** [comment]
@jayahm Hello,

It is not required to set the k value on the RRC model at all. By default it uses the whole DSEL which is the original version of those techniques.

We just allow the user to have more a bit more flexibility and limit the number of data points used in the calculation since it can significantly reduce computational cost when dealing with large datasets. But that is completely optional.

**Comment by jayahm** [comment]
I see. I got it. Thank you.
