### ISSUE TITLE
deslib for regression problem

### ISSUE THREAD

**Issue by maryam3066** [scikit-learn-contrib/DESlib#215]
Hi
can I use deslib library for predicting numerical values (regression problem)?

**Comment by Menelau** [comment]
@maryam3066 Hello, 

Unfortunately, the library doesn't have support for regression problems yet. All methods implemented are for classification only.

I have plans in the future to add dynamic selection techniques for regression such as the MINE framework: 

https://www.sciencedirect.com/science/article/pii/S0020025520307192?casa_token=3v_kQeVLhxkAAAAA:w24yRTt8uQXwIZ-dUCNbVtXXnjEMQ4owMSteAHT3WCYkfzyS7fqy9MIJNi22FgbApL6Z-mav0mI

But this addition will require a bit of work and code refactoring. Since the priority right now is to add the classification techniques that are still not available and improving the overall stability/code performance, regression techniques will only be worked on future releases (version 0.5).
