### ISSUE TITLE
Cannot find Online Local Pool

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#229]
Hi,

This method is listed in this paper: https://www.jmlr.org/papers/volume21/18-144/18-144.pdf

But, I couldn't find it in hits library.

**Comment by Menelau** [comment]
This code was moved to a specific branch: **olp_sgh**: https://github.com/scikit-learn-contrib/DESlib/blob/olp_sgh/deslib/dcs/olp.py

It was removed from the master code since it is missing the unit tests. If you want to use this code you can simply copy the olp.py and sgh.py files from this branch to your project.

**Comment by jayahm** [comment]
I see.

Okay, thanks for the clarification.
