### ISSUE TITLE
Can real time data be taken for DESlib

### ISSUE THREAD

**Issue by JSHAILAJA** [scikit-learn-contrib/DESlib#268]

**Comment by Menelau** [comment]
@JSHAILAJA Hello,

In the case what do you mean by real time data? Is it a dynamic environment in which data comes as a stream (online setting) instead of dealing with just a static block of data? If yes, DESlib does not offer this functionality natively. However, there are other Python libraries that uses the estimators from scikit-learn and put them in an environment that can deal with it. You you can check the scikit-Dyn2sel as one example: https://github.com/luccaportes/Scikit-DYN2SEL
