### ISSUE TITLE
Add example with different training sets and feature set

### ISSUE THREAD

**Issue by waldnerf** [scikit-learn-contrib/DESlib#73]
Hi, 
First, let me thank you for the good job you did with developing the library! 
Cruz et al. (2018) list six ways to generate classifiers, and two of them are the use of different **training sets** and **feature sets**.  Does the current implementation of DESlib allow that? Could you add such an example in the documentation?
Thanks, 
Franz

**Comment by Menelau** [comment]
Hi,

The current implementation of DESlib allows the use of different training sets (in the case each base classifier can be trained with a different partition of the data that could either be totally disjoint or not). 

Unfortunately, the current version of the library does not allow base classifiers trained with different **feature sets**. That would require changing the estimate_competence (mostly the way of defining the region of competence as the local region will change according to each different feature set), and predict methods so that the competence estimation and prediction of each base classifier are made on its corresponding feature space. I have plans to allow classifiers trained on different feature sets in the future since I really believe dynamic selection work well in this scenario.

About the examples, I think that is a good idea to add and link the examples in the documentation to the different ways of generating the base classifiers described in the paper. I will add a few more examples soon.

**Comment by waldnerf** [comment]
Hi
Thanks for your reply. 
Looking forward to the new examples and functionalities.

**Comment by Menelau** [comment]
New examples were added in the v0.3 release.
